# build environment
FROM node:13.12.0-alpine as build
WORKDIR /usr/src/app
COPY package.json ./
COPY . ./
RUN yarn
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]