version: "3"
services:
  react.app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start
  